### ISSUE TITLE
Generator ignores all groups except last one

### ISSUE THREAD

**Issue by emilzse** [curious-odd-man/RgxGen#31]
**Describe the bug**
When having a regex with several groups it ignores all except the last one

**To Reproduce**
1. `"^(1)|(2)$"`
2. 
```
RgxGen rgxGen = new RgxGen(regex);
StringIterator uniqueStrings = rgxGen.iterateUnique();
Set<String> strings = new HashSet<>();
uniqueStrings.forEachRemaining(strings::add);
return strings; // [2]
```

**Expected behavior**
It should return `[1, 2]`

**Screenshots**

**Environment (please complete the following information):**
 - RgxGen Version 1.1

**Comment by curious-odd-man** [comment]
Hello @emilzse .

It was an easy fix.
I'll keep ticket open for now, but this week i'll deploy 1.2-SNAPSHOT, so you will be able to test yourself.

I'll post a notification then.

Best Regards!

**Comment by curious-odd-man** [comment]
Hello @emilzse.

Version 1.2 Snapshot  is out live. Please refer to [Readme](https://github.com/curious-odd-man/RgxGen#latest-snapshot) how to use it, if you need that information.
