### ISSUE TITLE
Produce a sample that does not match a regex

### ISSUE THREAD

**Issue by spacether** [curious-odd-man/RgxGen#36]
Thank you so much for this package!
It looks great and I am looking forward to seeing if I can use it to generate regex samples for api documentation and test generation.

**Is your feature request related to a problem? Please describe.**
One can generate strings that do match a regex pattern but can it generate a string that does not match a pattern?
Your code lets us test a positive use case. If you provide a sample_does_not_match_pattern functionality then we can test the negative use case too.

**Describe the solution you'd like**
Could a method or function be created to produce a sample that does not match a regex pattern?

**Describe alternatives you've considered**
Randomly generating strings until a non matching sample is found.
But that is non-deterministic and is brute forcing the problem.

**Additional context**
I am considering using this library in https://github.com/OpenAPITools/openapi-generator

**Comment by curious-odd-man** [comment]
Hello @spacether .

Thank you for your ticket. 
Let me describe what solution I may be able to provide and please let me know if that solution will satisfy you.

**Solution**:

Suppose we have a regex: `abc[def]` - a simple one.

I would then separate this regex into 2 parts: `asd` and `[def]`.

To produce string that does not match the initial pattern I will;
1. Select `1 to N` parts (`N` is total number of parts - 2 in sample case) 
1. Invert each selected part. For example:
    1. For `abc` part I will produce random 3 character long string, that is not `abc`
    1. For `[def]` part I will change to `[^def]`
1. Generate a regex mixing "normal" parts and "inverted" parts.

This approach should produce strings that will partially match the regex.
I will also allow user to specify fraction of parts that should be inverted. 
For example if user specifies 1 - then all parts will be inverted. If user will specify 0 - then only 1 part will be inverted, and if user will specify 0.5 - then half of the parts will be inverted.

Is that approach is clear for you? Do you think that will suite your needs?

**Comment by spacether** [comment]
Yup, I think that that approach will suit my needs.
For now your library generating samples that match is the most important use case for us.

These not matching negative use cases are a nice to have for the future.
The most important need that we would have both for the matching and non matching samples is that wen we get the first sample that does or doesn't match, that it is constant.

If our pattern is:
`^def`
and we get:
first_match = `def`
first_non_match = `fed`
as long as those samples will always be those values that works for us.
We need this determinism because the samples are used to generate documentation and tests.
We don't want values changing with every sample generation invocation.

**Comment by curious-odd-man** [comment]
In current implementation you can provide initialized `Random`  to get same generated random values: `public String generate(Random random)`;
In not matching generation I will use same approach - if identical `Random`  will be provided - identical results will be returned.

You can refer to [this](https://github.com/curious-odd-man/RgxGen/blob/dev/src/test/java/com/github/curiousoddman/rgxgen/CombinedTests.java#L104) test case.

Random 3 character long string will be deterministic because randomness of this string will be defined by some of the pseudo-random values generators, e.g. `Random`,  which is deterministic. Refer to [this post](https://stackoverflow.com/questions/3583515/random-number-with-seed) for explanation.

**Comment by spacether** [comment]
That works great; thank you!

**Comment by curious-odd-man** [comment]
Hello. I've completed implementation for the feature requested. 
Please refer to README for usage.
It is available as a snapshot release. 

If something is not working or any additional features are needed - please open another ticket.

**Comment by spacether** [comment]
Thank you! Openapi generator is now using your package to generate matching regex examples for the python-experimental generator https://github.com/OpenAPITools/openapi-generator/pull/7157

**Comment by curious-odd-man** [comment]
That is great! Thank you. It's always nice to know that someone uses your work 👍
