### ISSUE TITLE
`\Q..\E` is not supported

### ISSUE THREAD

**Issue by eprst** [curious-odd-man/RgxGen#43]
`new RgxGen("\\Q.\\E").generate()` should build `"."`, not something like `"QmE"`.

Version 1.2

**Comment by curious-odd-man** [comment]
![image](https://user-images.githubusercontent.com/10796252/96331275-ad961400-1064-11eb-80c8-7565dc1f6c1a.png)
![image](https://user-images.githubusercontent.com/10796252/96331279-b555b880-1064-11eb-8e9e-a3f714b24c5a.png)
