### ISSUE TITLE
controllable number of repetitions

### ISSUE THREAD

**Issue by eprst** [curious-odd-man/RgxGen#45]
The number of repetitions generated by things like `*` and `+` is currently hardcoded at `100`. Would be nice to have control over this.

**Comment by curious-odd-man** [comment]
Implemented in 1.3-SNAPSHOT version.

**Comment by curious-odd-man** [comment]
Please refer to the documentation how to configure RgxGen. - [docs](https://github.com/curious-odd-man/RgxGen#configuration)
