### ISSUE TITLE
Support for case-insensitive string generation.

### ISSUE THREAD

**Issue by nheitz** [curious-odd-man/RgxGen#47]
This library looks like it's going to fulfill a need I have in certain cucumber tests rather nicely.  Primarily I am interested in the "Not matching" string functionality...but is there any way to indicate that the constructor argument for "regex" shuld be used in a case insensitive way?

**Comment by curious-odd-man** [comment]
Hello Nicholas! Thank you for your question.

Unfortunately there is no "case insensitive" option currently. I think I can implement this in a nearest future.

**Comment by curious-odd-man** [comment]
Hello @nheitz. You can try SNAPSHOT release for the case-insensitive generation. The release of version 1.3 (including this implementation is planned later this year).

**Comment by curious-odd-man** [comment]
Ah. btw. To enable case insensitive matching use:
```
        RgxGen rgxGen = new RgxGen("your awesome pattern");
        RgxGenProperties properties = new RgxGenProperties();
        RgxGenOption.CASE_INSENSITIVE.setInProperties(properties, true);
        rgxGen.setProperties(properties);
```

**Comment by nheitz** [comment]
amazing.  Thank you very much.
