### ISSUE TITLE
Support for positive Look(ahead|behind) syntax

### ISSUE THREAD

**Issue by jamesbarrett95** [curious-odd-man/RgxGen#5]
As per the title, it would be great to see support for the positive look ahead regex syntax. :)

**Comment by curious-odd-man** [comment]
Given pattern `foo(?=bar)`
Expected output is `foobar`
Is that the expected behavior?

**Comment by curious-odd-man** [comment]
![image](https://user-images.githubusercontent.com/10796252/70333895-0691fa80-184d-11ea-8784-7998fb7cfbc4.png)
![image](https://user-images.githubusercontent.com/10796252/70333909-114c8f80-184d-11ea-9b18-8a0fbed819a7.png)
![image](https://user-images.githubusercontent.com/10796252/70333919-190c3400-184d-11ea-8b25-0fc77a6ac94e.png)
![image](https://user-images.githubusercontent.com/10796252/70333938-21fd0580-184d-11ea-8887-ba5fe1bea275.png)

**Comment by curious-odd-man** [comment]
Positive done in ecfea495
Negative will be done in another issuse
