### ISSUE TITLE
Are regex flags supported?

### ISSUE THREAD

**Issue by spacether** [curious-odd-man/RgxGen#57]
**Is your feature request related to a problem? Please describe.**
Are regex flags supported? I would like them to be used when generating samples.

Per:
- https://www.ecma-international.org/ecma-262/5.1/#sec-15.10.7.2
- https://docs.python.org/3/library/re.html#re.compile
Flags can be global, ignore_case and multi_line

**Describe the solution you'd like**
One where we can pass in the flags in the regex input string.

**Describe alternatives you've considered**
N/A

**Additional context**
This came up when reviewing https://github.com/OpenAPITools/openapi-generator/pull/8054#pullrequestreview-555587102

**Comment by curious-odd-man** [comment]
Hello @spacether .

At the moment flags are not supported.

The ignore_case (case insensitive generation) can be turned on using [configuration](https://github.com/curious-odd-man/RgxGen#configuration) object and [this](https://github.com/curious-odd-man/RgxGen/blob/dev/src/main/java/com/github/curiousoddman/rgxgen/config/RgxGenOption.java#L38) option.

The generated values are always `multiline` - you can specify `^` and `$` character to mark start/end of string and `\n` or `\r\n` or `\r` of new line.

As for `global` flag - I don't see how it fits in generation of text by pattern.
Please let me know if you want some specific behavior with/without `global` flag.

In general I will implement parsing of the ECMA format and parsing flags, though as far as I see I will ignore `g` and `m` flags. And `i` flag will set the parameter for case insensitive generation.

This will be done as part of #56 issue. 

Please add details/examples if you expect some specific behavior (different behavior) for `g` and `m` flags or close the ticket if you agree with what I wrote above.

**Comment by spacether** [comment]
Thank you for explaining that.
I agree that global has no impact so it makes sense to omit it.
It looks like when not in multiline mode then ^ will only match the beginning of the passed in string and when in multiline mode it will match the beginning of the string and before all newlines. Do you agree with that interpretation? Could a multiline True/False option be added to your Configuration?

Here is a sample of what could be generated with MULTILINE=True/False
`pattern = '^a'`

MULTILINE=False
- generated_examples = ['a']

MULTILINE=TRUE
- generated_examples = ['a', '\na', '\n\na']

**Comment by curious-odd-man** [comment]
Another issue is created for multiline generation - #58 .
Case insensitive generation is supported by configuration option and will be supported with flags when #56 is done.

**Comment by spacether** [comment]
Thank you!
