### ISSUE TITLE
iterateUnique().current() causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Kaljurand** [curious-odd-man/RgxGen#59]
The call to "iterateUnique().current()" sometimes crashes, e.g.

```
import com.github.curiousoddman.rgxgen.RgxGen;
import com.github.curiousoddman.rgxgen.iterators.StringIterator;

public class MyClass {
    
    public static String PATTERN = "[ab]";
    
    public static void main(String args[]) {
        RgxGen rgxGen = new RgxGen(PATTERN);
        StringIterator uniqueStrings = rgxGen.iterateUnique();
        System.out.println(uniqueStrings.current());
    }
}
```

results in:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 2
	at com.github.curiousoddman.rgxgen.iterators.ArrayIterator.current(ArrayIterator.java:55)
	at MyClass.main(MyClass.java:11)
```

The result is "a" if the pattern is changed to "(a|b)" and/or the call is changed to "next()". The issues are:

- this behavior is inconsistent
- the difference between ``current`` and ``next`` is unclear
- the crash should not happen

(Thanks for the cool library, btw.)

**Comment by curious-odd-man** [comment]
Hello @Kaljurand .

Thank you for reporting the issue.

This is in general normal behavior.

`StringIterator` is a slight extension to `java.util.Iterator<String>`. The addition is `current()` method.

So the proper usage for the `StringIterator` is.

```
StringIterator it = ....
while (it.hasNext()) {
    String s = it.next();
}
```

The `current()` method mostly implemented for the internal needs and it only is used to get the same value as returned by last call to `next()`. Thus, calling `current()` before `next()` results in unspecified behavior.

I will do following thing to make it clearer and more user-friendly, though:

- [ ] Javadoc for the `StringIterator` class should clearly state how to use it properly
- [ ] Investigate if it is possible having consistent behavior - if `current()` is called before `next()` throw clear exception
- [ ] Investigate if I need method `next()` calling always `nextImpl()` or I can simplify that to just having `next()`

Please let me know if you would like to add anything.

**Comment by curious-odd-man** [comment]
I've decided to ignore issue with unspecified behavior with `current()` method call.

The reason:

Purely for performance reasons. To implement this I would need introduce flag in each iterator (and do redundant assignment on each call to `next()`. Additionally I would need to check the flag on each call to `current()`. These are two redundant actions that would be executed pretty much. I would like to avoid extra operations. I think the documentation should be enough for correct usage in this case.
