### ISSUE TITLE
Can use "Unicode Regular Expressions" in pattern? 

### ISSUE THREAD

**Issue by shredd0r** [curious-odd-man/RgxGen#67]
Can use "Unicode Regular Expressions" in pattern?

Now, if use the expressions, library generate str with symbol from expression

example:

`fnew RgxGen("\\u0041").generate()` 

expected:  `result: "A"`

actual:  `u0041`

**Comment by curious-odd-man** [comment]
Hello!

The change is implemented and deployed as Snapshot - `<version>1.4-SNAPSHOT</version>` to `https://oss.sonatype.org/content/repositories/snapshots`- feel free to try it.

Alternatively version 1.3 already supports unicode characters, though in a slightly different format:
```
// Hex character:
 xNN or \x{NNNN}
```
would behave exactly the same.

**Comment by shredd0r** [comment]
thx
