### ISSUE TITLE
JDoodle is broken

### ISSUE THREAD

**Issue by LinqLover** [curious-odd-man/RgxGen#72]
Referring to the link in the readme: https://www.jdoodle.com/a/2Q6T

It just says: Unable to process your request. Please try again, or contact JDoodle Support at hello@jdoodle.com.

It would be great to get that fixed as a fast try-out example might attract more potential users of the tool.

**Comment by curious-odd-man** [comment]
Hello @LinqLover ! 

Thank you very much for reporting that.
Unfortunately something is wrong with project share in Jdoodle. 
I've reported this issue to them and hope that they will fix it soon.

For the time being you still can try out the library on Jdoodle
1. Create a project there
2. In java file copy/paste code
``` 
import com.github.curiousoddman.rgxgen.RgxGen;

public class MyClass {
    
    // Enter your pattern here.
    public static String PATTERN = "(a|b|c){3,5}";
    
    public static void main(String args[]) {
        RgxGen rgxGen = new RgxGen(PATTERN);
        System.out.println("10 matching: ");
        for (int i = 0; i < 10; ++i) {
            System.out.println("\t" + rgxGen.generate());
        }
        System.out.println("10 non-matching: ");
        for (int i = 0; i < 10; ++i) {
            System.out.println("\t" + rgxGen.generateNotMatching());
        }
        
    }
}
``` 
And the add library to dependecies:
![image](https://user-images.githubusercontent.com/10796252/227709504-cfd998f7-bffc-4c7c-8952-b3a51e0c9d5e.png)

![image](https://user-images.githubusercontent.com/10796252/227709521-a100ceb7-e912-4408-9171-455dda321591.png)

`com.github.curious-odd-man:rgxgen:1.3`

**Comment by curious-odd-man** [comment]
Glad to hear that! Let me know if you find something that does not work, but is required. :)
