### ISSUE TITLE
`\p` is not supported (Character classes)

### ISSUE THREAD

**Issue by puskarpeter** [curious-odd-man/RgxGen#73]
Add support for character classes specified with `\p`.
`new RgxGen("\\p{InBasicLatin}{0,255}").generate()` should generate an example from Unicode characters in BasicLatin class.
Currently it fails with `NumberFormatException` since the expresion in `{}` is treated as repetition block.

**Version 1.4**

**Comment by curious-odd-man** [comment]
Documentation about categories
https://www.regular-expressions.info/unicode.html#category

**Comment by curious-odd-man** [comment]
Hello @puskarpeter ! This is now supported. I would very much like your feedback. You can use snapshot `1.5-SNAPSHOT` to try this out. 
The release 1.5 is planned as soon as I get through with few more items.
