### ISSUE TITLE
Any chance for a release of this library?

### ISSUE THREAD

**Issue by bodiam** [curious-odd-man/RgxGen#93]
Hi,

We would love to use the 2.0 version of this library in Datafaker, but it seems there's only a 2.0 SNAPSHOT available, on which we can't depend.

Would it be possible to publish a 2.0 version of this library in the near future?

Cheers,
Erik

**Comment by curious-odd-man** [comment]
Hello!

I will work on that!
Do you have any hard deadlines?

Best Regards,
Vlad

**Comment by bodiam** [comment]
Hi @curious-odd-man , thanks for the quick response. 

Both our projects are open source, it's a labor of love, so absolutely no deadlines. We are currently using a different Regex library, but it has a few issues and is no longer maintained, and we'd love to use yours when you have a non-snapshot version available. Thanks for your work on this library!

**Comment by curious-odd-man** [comment]
Hello. 

I've release 2.0.
``` 
<dependency>
    <groupId>com.github.curious-odd-man</groupId>
    <artifactId>rgxgen</artifactId>
    <version>2.0</version>
</dependency>
```

Happy using :)

**Comment by bodiam** [comment]
Thank you for the quick work! We're now using your library here: https://github.com/datafaker-net/datafaker
